spring.application.name=demo
# 1. Dirección, puerto y nombre de la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/licoreria_dcorleone?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# 2. Usuario y Contraseña de tu MySQL local
spring.datasource.username=root
spring.datasource.password=clavemanuel

# 3. Driver de conexión para MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Configuración extra de Hibernate (JPA) para que valide la estructura de las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
